import type { Metadata } from 'next'
import { Courier_Prime } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/auth/components/AuthProvider'

const curier = Courier_Prime({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="es">
        <body className={`${curier.className}`}>{children}</body>
      </html>
    </AuthProvider>
  )
}
