import { Providers } from '@/providers'
import type { Metadata } from 'next'
import { Courier_Prime } from 'next/font/google'
import './globals.css'

const curier = Courier_Prime({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${curier.className}`}>{children}</body>
      </html>
    </Providers>
  )
}
