name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 18.x ]

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}


    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.9
          run_install: false

      - run: pnpm i
      - run: pnpm build --if-present
      - run: pm2 reload gastos
        env: 
          DATABASE_URL: ${{env.DATABASE_URL}}
          GOOGLE_CLIENT_ID: ${{env.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{env.GOOGLE_CLIENT_SECRET}}
          NEXTAUTH_SECRET: ${{env.NEXTAUTH_SECRET}}
          NEXTAUTH_URL: ${{env.NEXTAUTH_URL}}

